# Generated by Django 5.0 on 2023-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
