# Generated by Django 5.0 on 2023-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(blank=True, default='link', max_length=1000, null=True),
        ),
    ]
